### PR TITLE
The parameter expects a Community type when it actually uses an int t…

### PR DESCRIPTION
**Pull request by extremq**
…ype.

IDE RAISES ERRORS BECAUSE OF THIS 😡😡😡

### CODE REVIEW

**Comment by Athesdrake** [comment]
It accepts both the type `int` and the enumeration `Community`. Therefore, the type should be an union of both: `Union[Community, int]`.
I'll merge once you fix this.

**Comment by extremq** [comment]
Done!! :)

**Comment by extremq** [comment]
And by the way, incredible library!!

**Comment by Athesdrake** [comment]
> 
> 
> And by the way, incredible library!!

It's thanks to people like you that helps me improving it!

**Pull request merged**
